### ISSUE TITLE
[OPS] Problems with kibana

### ISSUE THREAD

**Issue by hugoArregui** [decentraland/world#40]
https://trello.com/c/mdUQYCGm
https://trello.com/c/Yz7Dt9Zw

**Comment by adrabenche** [comment]
Using AWS ES service
We were able to set it up
auto backup
Log index splitted by date and log stream

conecting dev accounts

**Comment by adrabenche** [comment]
Using logstash from Fargate and EK from AWS. I can see the logs are coming; but some parsing errors

```[2019-07-22T20:03:51,426][WARN ][logstash.filters.json ] Error parsing json {:source=>"message", :raw=>"time=\"2019-07-17T18:31:19.630\" level=debug msg=\"Request received at endpoint: GetScenes\" func=github.com/decentraland/content-service/handlers.ResponseHandler.ServeHTTP file=\"/go/src/github.com/decentraland/content-service/handlers/handlers.go:72\"", :exception=>#<LogStash::Json::ParserError: Unrecognized token 'time': was expecting 'null', 'true', 'false' or NaN```

**Comment by hugoArregui** [comment]
I created the new index patterns. Ale don't worry about those errors, the messages are truly not json so it's expected. Everything seems to be working perfectly fine!
