### ISSUE TITLE
Profile schema should have Ethereum address and proof signature of userid

### ISSUE THREAD

**Issue by eordano** [decentraland/world#88]
These two fields should not be returned by default on profile descriptions. Current users might query what is the Ethereum address associated with their profile

**Comment by hugoArregui** [comment]
Likely we will have to do this as discussed in https://docs.google.com/document/d/19b7b9detHtENQH23fNHO8OozE5Yh2rNuI1aDQtSDLrc/edit?ts=5d482c4b but I will close this issue until we have a use case for it.
